-- Migration to add SaaS fields to Company table
ALTER TABLE company ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'active';
ALTER TABLE company ADD COLUMN IF NOT EXISTS plan VARCHAR(50) DEFAULT 'pro';
ALTER TABLE company ADD COLUMN IF NOT EXISTS max_users INTEGER DEFAULT 5;
ALTER TABLE company ADD COLUMN IF NOT EXISTS max_leads INTEGER DEFAULT 1000;
ALTER TABLE company ADD COLUMN IF NOT EXISTS max_storage_gb FLOAT DEFAULT 1.0;
ALTER TABLE company ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW();
