-- Database Schema Backup: 2026-01-18
-- Produced by Antigravity AI

CREATE TABLE client (address_city character varying, address_neighborhood character varying, address_number character varying, address_street character varying, niche character varying, notes text, document character varying, lead_id integer, start_date date NOT NULL, monthly_value double precision, renewal_date date, created_at timestamp without time zone, name character varying NOT NULL, account_manager_id integer NOT NULL, email character varying, phone character varying, status character varying, health_status character varying, service character varying, id integer NOT NULL, contract_type character varying, company_id integer NOT NULL, profile_pic_url character varying, email_contact character varying, representative_cpf character varying, representative character varying, address_zip character varying, address_state character varying);
CREATE TABLE client_checklist (updated_at timestamp without time zone, id integer NOT NULL, client_id integer NOT NULL, template_id integer, company_id integer, progress json NOT NULL, name character varying NOT NULL, created_at timestamp without time zone);
CREATE TABLE company (representative character varying, logo_filename character varying, representative_cpf character varying, address_zip character varying, address_state character varying, address_city character varying, address_neighborhood character varying, address_number character varying, address_street character varying, document character varying, name character varying NOT NULL, plan character varying, status character varying, secondary_color character varying, primary_color character varying, id integer NOT NULL, created_at timestamp without time zone, max_users integer, max_leads integer, max_storage_gb integer);
CREATE TABLE contract (signed_at timestamp without time zone, expires_at date, issued_at timestamp without time zone, lead_id integer, template_id integer, id integer NOT NULL, content text NOT NULL, canceled_at timestamp without time zone, cancellation_reason text, cancellation_penalty double precision, cancellation_due_date date, client_id integer, status character varying, company_id integer NOT NULL);
CREATE TABLE contract_template (is_library boolean, is_global boolean, content text NOT NULL, id integer NOT NULL, company_id integer, name character varying NOT NULL, description text, created_at timestamp without time zone);
CREATE TABLE goal (year integer NOT NULL, id integer NOT NULL, mrr_target double precision, new_clients_target integer, company_id integer NOT NULL, month integer NOT NULL);
CREATE TABLE interaction (lead_id integer, type character varying NOT NULL, content text NOT NULL, created_at timestamp without time zone, client_id integer, user_id integer, id integer NOT NULL);
CREATE TABLE lead (notes text, bant_authority character varying, bant_need text, bant_timeline character varying, website character varying, address character varying, profile_pic_url character varying, bant_budget character varying, id integer NOT NULL, status character varying, name character varying NOT NULL, phone character varying, email character varying, source character varying, pipeline_id integer NOT NULL, pipeline_stage_id integer, company_id integer NOT NULL, created_at timestamp without time zone, assigned_to_id integer, client_id integer, interest character varying);
CREATE TABLE notification (read boolean, id integer NOT NULL, user_id integer NOT NULL, company_id integer NOT NULL, created_at timestamp without time zone, type character varying NOT NULL, title character varying NOT NULL, message text NOT NULL);
CREATE TABLE pipeline (id integer NOT NULL, company_id integer NOT NULL, name character varying NOT NULL, description text, created_at timestamp without time zone);
CREATE TABLE pipeline_stage (id integer NOT NULL, pipeline_id integer NOT NULL, company_id integer NOT NULL, name character varying NOT NULL, order_index integer NOT NULL);
CREATE TABLE process_template (id integer NOT NULL, company_id integer, name character varying NOT NULL, description text, steps json NOT NULL, created_at timestamp without time zone);
CREATE TABLE role (id integer NOT NULL, name character varying NOT NULL, description text);
CREATE TABLE task (lead_id integer, priority character varying, status character varying, recurrence character varying, title character varying NOT NULL, description text, company_id integer NOT NULL, assigned_to_id integer, client_id integer, completed_at timestamp without time zone, is_recurring boolean, reminder_sent boolean, due_date timestamp without time zone, id integer NOT NULL);
CREATE TABLE template_company_association (company_id integer, template_id integer);
CREATE TABLE transaction (contract_id integer, company_id integer, amount double precision NOT NULL, due_date date NOT NULL, paid_date date, client_id integer, created_at timestamp without time zone, installment_number integer, asaas_invoice_url character varying, asaas_id character varying, cancellation_reason text, status character varying, description character varying NOT NULL, total_installments integer, id integer NOT NULL);
CREATE TABLE "user" (supabase_uid character varying, onboarding_dismissed boolean, is_super_admin boolean, created_at timestamp without time zone, company_id integer, role_id integer, id integer NOT NULL, status_message character varying, phone character varying, profile_image character varying, role character varying NOT NULL, password_hash character varying NOT NULL, name character varying NOT NULL, email character varying NOT NULL);
CREATE TABLE user_pipeline_association (pipeline_id integer, user_id integer);
CREATE TABLE whats_app_message (status character varying, external_id character varying, direction character varying NOT NULL, type character varying, content text, created_at timestamp without time zone, client_id integer, company_id integer NOT NULL, lead_id integer, id integer NOT NULL);
